sudo: true
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
			addons:
			  apt:
			    sources:
			      - george-edison55-precise-backports
			    packages:
			      - cmake-data
			      - cmake
			      
before_install:
  - apt-get update -qq
  - apt-get install -y libopencv-dev
        
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ../source && make
  
branches:
  only:
    - master

notifications:
  email: false