sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      addons:
			  apt:
			    sources:
			      - george-edison55-precise-backports
			    packages:
			      - cmake-data
			      - cmake
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      addons:
			  apt:
			    sources:
			      - george-edison55-precise-backports
			    packages:
			      - cmake-data
			      - cmake            
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      addons:
			  apt:
			    sources:
			      - george-edison55-precise-backports
			    packages:
			      - cmake-data
			      - cmake            
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      addons:
			  apt:
			    sources:
			      - george-edison55-precise-backports
			    packages:
			      - cmake-data
			      - cmake            
      env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
        
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ../source && make
  
branches:
  only:
    - master

notifications:
  email: false